### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by ramtinabadi** [Vieolo/vieolo-ui#215]
https://sass-lang.com/documentation/variables/#flow-control-scope

The above link is provided by SCSS. However, it doesn't work for us.
The following approach should be made:

```SCSS
:root {
  --primary-color: #f8bbd0;
  --accent-color: #6a1b9a;
}

.dark-theme {
  --primary-color: darken(#f8bbd0, 60%);
  --accent-color: lighten(#6a1b9a, 60%);
}

$primary-color: var(--primary-color);
$accent-color: var(--accent-color);

.button {
  background-color: $primary-color;
  border: 1px solid $accent-color;
  border-radius: 3px;
}
```

Here, the colors are defined in a normal CSS variable and then re-assigned to SCSS variables. To turn on the dark mode, the `dark-mode` CSS class should be added to the body.

> [!IMPORTANT]
> The only problem to figure out is how to allow the implementer to override the SCSS color variables and don't break the dark mode implementation
