### ISSUE TITLE
[Chip] Explicitly apply the color of the text

### ISSUE THREAD

**Issue by ramtinabadi** [Vieolo/vieolo-ui#289]
The text of the chip is wrapped in a `p` element.
If the implementor has a css rule like:
```css
p {
    color: black;
}
```

then the color of the text in the chip won't match the emphasis and color
