### ISSUE TITLE
Add CSS class for List component

### ISSUE THREAD

**Issue by ramtinabadi** [Vieolo/vieolo-ui#33]
The css class should be:
```css
.vieolo-list {
	width: 100%;
	overflow: scroll;
}
```
